#!/usr/bin/env ruby
# !!!!!!!!!! make sure to use same RUBY version that macvim was compiled with
# !!!!!!!!!! to compile command-t (last step here), or result in unstable

  # ctrlp is better
  #"git://github.com/vim-scripts/L9.git",
  #"git://github.com/vim-scripts/FuzzyFinder.git",
  #"git://github.com/sethbc/fuzzyfinder_textmate.git"

  #
  # NOTE: Here are some other vim projects you may
  # want to include in your Vim build.  I'm currently
  # not using these, so I've commented the below for now.
  #
  #"git://github.com/gregsexton/gitv.git",
  #"git://github.com/nanotech/jellybeans.vim.git",
  #"git://github.com/vim-scripts/mru.vim.git",
  #"git://github.com/vim-scripts/project.tar.gz.git",
  #"git://github.com/nathanaelkane/vim-indent-guides.git",
  #"git://github.com/vim-scripts/LustyJuggler.git",
  #"git://github.com/tsaleh/vim-shoulda.git",
  #"git://github.com/tpope/vim-git.git",
  #"git://github.com/tpope/vim-haml.git",
  #"git://github.com/tpope/vim-markdown.git",
  #"git://github.com/tpope/vim-cucumber.git",
  #"git://github.com/godlygeek/tabular.git",
  #"git://github.com/msanders/snipmate.vim.git",
  #"git://github.com/timcharper/textile.vim.git",
  #"git://github.com/pangloss/vim-javascript.git",
  #"git://github.com/tsaleh/vim-tmux.git",
  #"git://github.com/vim-scripts/Gist.vim.git",
  #"git://github.com/tpope/vim-surround.git",
  #"git://github.com/vim-ruby/vim-ruby.git",
  #"git://github.com/tpope/vim-repeat.git",
  #"git://github.com/tpope/vim-rails.git",
  #"git://github.com/wincent/Command-T.git",

git_bundles = [ 
  "git://github.com/tpope/vim-pathogen.git",
  "git://github.com/scrooloose/syntastic.git",
  "git@github.com:dhallman/Specky.git",
  "git://github.com/tpope/vim-endwise.git",
  "git@github.com:dhallman/bufexplorer.git",
  "git://github.com/vim-scripts/Color-Sampler-Pack.git",
  "git://github.com/ervandew/supertab.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tsaleh/vim-matchit.git",
  "git://github.com/vim-scripts/ZoomWin.git",
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/rosenfeld/conque-term.git",
  "git://github.com/vim-scripts/LustyExplorer.git",
  "git://github.com/lucapette/codepath.vim.git",
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/vincentv/dotvim.git",
  "git://github.com/tpope/vim-bundler.git",
  "git://github.com/tpope/vim-rvm.git",
  "git://github.com/kien/ctrlp.vim.git"
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(ENV["HOME"], ".vim", "bundle")
puts "bd == #{bundles_dir}"

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git")) unless url.include? 'dhallman'
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

##  Using ctrlp instead
#puts "Building Command-T C Extensions"
#commandt_dir = File.join(ENV["HOME"], ".vim", "bundle", "Command-T")
#FileUtils.cd(commandt_dir)
#`bundle install && rake make`
